require('plugins')
require('basics')
require('treesitter')
-- require('backup')
require('keybindings')
require('search')
require('characters')
require('lsp_config')
require('mapping')
require('header')
require('protection')
